Repository arduino-libraries/MKRGSM, pull requests merged in 2021-12, with the labels that each got.

#142 Adding sync-labels workflow for sharing one set of labels across all repos.
  .github/workflows/sync-labels.yml
Labels: enhancement

#143 Fixing CI build of examples/eraseAllCertificates:
  examples/SSLCertificateManagement/SSLCertificateManagement.ino
Labels: type: enhancement, topic: code

#144 Fix examples `HttpUtilsGet`/`HttpUtilsSSLGet`
  examples/Tools/HttpUtilsGet/HttpUtilsGet.ino
  examples/Tools/HttpUtilsSSLGet/HttpUtilsSSLGet.ino
Labels: type: enhancement

#146 Use major version ref of `carlosperate/download-file-action`
  .github/workflows/sync-labels.yml
Labels: type: enhancement, topic: infrastructure
